# Generated by Django 5.1.7 on 2025-03-19 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OfficeDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('office_name', models.CharField(blank=True, max_length=50, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('building_no', models.BigIntegerField(blank=True, null=True)),
                ('district', models.CharField(blank=True, max_length=80, null=True)),
                ('local_body', models.CharField(blank=True, max_length=70, null=True)),
            ],
        ),
    ]
