# Generated by Django 5.2.1 on 2025-06-03 15:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('section_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=40, null=True)),
                ('dp', models.ImageField(blank=True, null=True, upload_to='profile')),
                ('city', models.CharField(blank=True, max_length=20, null=True)),
                ('house_no', models.CharField(blank=True, max_length=10, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('consumer_id', models.BigIntegerField(blank=True, null=True)),
                ('sectionoffice', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='section_app.officedetails')),
                ('user_details', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
